name: lug

services:
  db-postgres:
    # https://hub.docker.com/_/postgres
    image: "postgres:${PSQL_VERSION}-alpine"
    ports:
      - "5400:5432"
    restart: "on-failure"
    shm_size: 256mb
    environment:
      POSTGRES_PASSWORD: "${PSQL_ROOT_USER_PASS}"
      POSTGRES_USER: "${PSQL_ROOT_USER_NAME}"
      POSTGRES_DB: "${PSQL_ROOT_DB}"
      POSTGRES_INITDB_ARGS: "--auth=${PSQL_AUTH_METHOD}"
      PGDATA: "/var/lib/postgresql/data"
    volumes:
      - "vol-postgres:/var/lib/postgresql/data"

volumes:
  vol-postgres:
